# Site settings
name: MyNEU
username: Brittany
fullname: Brittany Chiang
nuid: 001937003
title: Redesign myNEU
description:
url: http://brittanychiang.com
baseurl: ""
logo: http://www.northeastern.edu/nurugby/wp-content/themes/nurugby/img/SplitN.png
avatar: http://nuwit.ccs.neu.edu/img/officers/brittany2.jpg
email:
social:
  - title: email
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
