# Site settings
name: MyNEU
title: Redesign myNEU
description:
url: http://brittanychiang.com
baseurl: ""
logo: img/n-logo.png
email:
social:
  - title: email
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
